-o<int>
<id,main>
<(>
<)>
<{>
<int>
<id,string>
<[>
<intd>
ExpNumber:0
<]>
<;>
<int>
<id,temp>
<;>
<int>
<id,i>
<;>
<int>
<id,count>
<;>
<id,count>
<=>
Lval
<into>
ExpNumber:0
<;>
stmt1
<id,i>
<=>
Lval
<into>
ExpNumber:0
<;>
stmt1
<id,temp>
<=>
Lval
<into>
ExpNumber:0
<;>
stmt1
<while>
<(>
<id,temp>
<!=>
Lval
<intd>
ExpNumber:0
<)>
<{>
<id,temp>
<=>
Lval
<id,getch>
<(>
<)>
<;>
stmt1
<if>
<(>
<id,temp>
<>>
Lval
<intd>
ExpNumber:0
<&&>
<id,temp>
<<>
Lval
<intd>
ExpNumber:0
<||>
<id,temp>
<>>
Lval
<intd>
ExpNumber:0
<&&>
<id,temp>
<<>
Lval
<intd>
ExpNumber:0
<)>
<{>
<id,count>
<=>
Lval
<id,count>
<+>
Lval
<intd>
ExpNumber:0
<;>
stmt1
<}>
<id,i>
<=>
Lval
<id,i>
<+>
Lval
<intd>
ExpNumber:0
<;>
stmt1
<}>
<id,putint>
<(>
<id,count>
<)>
Lval
<;>
<return>
<into>
ExpNumber:0
<;>
<}>
789
789
789
456
789
789
789
456
789
789
789
456
789
789
789
789
456
789
789
789
789
456
789
789
789
789
789
789
789
789
789
789
789
789
789
789
789
terminate called after throwing an instance of 'std::runtime_error'
  what():  TraverseScopeStack no result
Aborted (core dumped)
